<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllCustomersByGivenOrder(string $order)
    {
        return $this->createQueryBuilder('customer')
            ->orderBy('customer.birthDate', ':order')
            ->setParameter('order', $order)
            ->getQuery()
            ->getResult();
    }
}
